### ISSUE TITLE
browser.setupInterceptor is not a function

### ISSUE THREAD

**Issue by psswf1172** [chmanie/webdriverajax#11]
Was hoping to implement this to read request headers, so tried out the example code and got this error:
`browser.setupInterceptor is not a function`
`running chrome`
`TypeError: browser.setupInterceptor is not a function
    at Context.<anonymous> (/Users/.../test/analytics.js:14:13)
    at Promise.F (/usr/local/lib/node_modules/wdio-mocha-framework/node_modules/core-js/library/modules/_export.js:35:28) `

Here's the relevant set up details: 
`"node": "^6.10"`
`"selenium-standalone": "^6.12.0",`
`"webdriverajax": "^2.1.0",`
`"webdriverio": "^4.9.11",`

    browser.url("https://mywebapp.com/");
    browser.setupInterceptor();
    browser.click("body > main > section:nth-child(1) > div > a");
    browser.waitForVisible("#id-to-get");
    var request = browser.getRequest(0);

Any suggestions on how to get this working?  If it works this plugin could be a lifesaver.  :)

**Comment by chmanie** [comment]
Hey thanks for reporting the issue. I'm seeing issues with the newest versions of webdriver.io and selenium-standalone as well. Let me investigate that. For now you could go back to the versions defined in the devDependencies in webdriverajax:

```
"webdriverio": "^4.6.2"
"selenium-standalone": "^6.2.0"
```

as these work for sure. If that's not an option for you, unfortunately you'll have to be a bit patient.

**Comment by chmanie** [comment]
Please try version 2.1.1. Also make sure to put the `webdriverajax` plugin into your `wdio.conf`: https://github.com/chmanie/webdriverajax#using-with-wdio

**Comment by psswf1172** [comment]
Thanks -- I tried going back to the versions defined in the devDependencies as you suggested. And then using version 2.1.1 with the matching versions in devDependencies. 

Both ways I ran into the same issue: 

When the plugin in is listed in wdio.conf.js `    plugins: {
        webdriverajax: {}
    },` the module cannot be found. 

```
ERROR: Couldn't find plugin "webdriverajax". You need to install it with "$ npm install webdriverajax"!
Error: Cannot find module "webdriverajax"
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Runner.initialisePlugins (/usr/local/lib/node_modules/webdriverio/build/lib/runner.js:628:34)
    at Runner._callee$ (/usr/local/lib/node_modules/webdriverio/build/lib/runner.js:103:38)
    at tryCatch (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)

    at Runner.initialisePlugins (/usr/local/lib/node_modules/webdriverio/build/lib/runner.js:634:31)
    at Runner._callee$ (/usr/local/lib/node_modules/webdriverio/build/lib/runner.js:103:38)
    at tryCatch (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

And when I comment out the plugin in wdio.conf.js, 
```
1) request includes analytics includes this_call:
browser.setupInterceptor is not a function
running chrome
TypeError: browser.setupInterceptor is not a function
    at Context.<anonymous> (/Users/.../test/analytics.js:14:13)
    at Promise.F (/usr/local/lib/node_modules/wdio-mocha-framework/node_modules/core-js/library/modules/_export.js:35:28)
```
It must be something I'm doing wrong elsewhere which I cannot figure out for the life of me.

**Comment by chmanie** [comment]
Hm. I'm assuming that you did a
```
npm install webdriverajax
```
in your working directory.

Please make sure that it is also noted in the package.json. You can ensure that by doing
```
npm install webdriverajax --save-dev
```

I tried exactly that and it worked for me. If you're still having troubles join the gitter room here: https://gitter.im/chmanie/webdriverajax and I'll try to sort you out (if I'm there).

**Comment by chmanie** [comment]
I think 2.1.1 was not yet published. My mistake. Please try again.
