### ISSUE TITLE
Integration with Gulp

### ISSUE THREAD

**Issue by ayxos** [chmanie/webdriverajax#8]
How can i integrate this with my current gulp setup? 
conf:
```
const Launcher = require('webdriverio/build/lib/launcher');
const path = require('path');
var wdajax = require('webdriverajax');
const wdio = new Launcher(path.join(__dirname, 'wdio.conf.js'));
...
gulp.task('e2e', () => {
  wdajax.init(wdio);
  return wdio.run(code => {
    process.exit(code);
  }, error => {
    console.error('Launcher failed to start the test', error.stacktrace);
    process.exit(1);
  });
});
```

I got this error:
``` 
[17:56:58] Using gulpfile ~/projects/adTag2/gulpfile.js
[17:56:58] Starting 'e2e'...
[17:56:58] 'e2e' errored after 397 μs
[17:56:58] Error: you can't use WebdriverAjax with this version of WebdriverIO
    at Object.plugin [as init] (/Users/marco/projects/adTag2/node_modules/webdriverajax/index.js:11:15)
    at Gulp.gulp.task (/Users/marco/projects/adTag2/gulpfile.js:170:10)
    at module.exports (/Users/marco/projects/adTag2/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/marco/projects/adTag2/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/marco/projects/adTag2/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/marco/projects/adTag2/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
```

Although my version is higher than v3

**Comment by chmanie** [comment]
I think it also does not work with v2. I will look into that though.

**Comment by chmanie** [comment]
I pushed a new version (v2) which should work with webdriverio v4.
